services:
    web:
        container_name: chuva
        build:
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src
            - ./public:/app/public
