FROM node:22-alpine

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json ./
RUN \
  if [ -f package.json ]; then npm i; \
  elif [ -f package-lock.json ]; then npm ci; \
  # Allow install without lockfile, so example works even without Node.js installed locally
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

COPY src ./src
COPY public ./public
COPY jsconfig.json ./

CMD \
  if [ -f package-lock.json ]; then npm start; \
  else npm start; \
  fi